language: minimal
env:
  global:
    - CI=true
    - COMMIT_SHA=${TRAVIS_COMMIT}
jobs:
  include:
    - stage: validate
      script: |
        while IFS= read -r line; do echo "Linting ${line}"; docker run --rm -v ${PWD}:/data mivok/markdownlint --rules ~MD013,~MD033,~MD034 "${line}" || exit 1; done < <(git ls-files '*.md')
    - stage: run
      script: |
        # Build a local version of the docs
        docker run --rm -v ${PWD}/site:/site -v ${PWD}:/docs squidfunk/mkdocs-material build --verbose --clean --strict
      before_deploy:
        - "sudo cp ${PWD}/CNAME ${PWD}/site/"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
        local_dir: site
matrix:
  fast_finish: true
